version: "3.7"

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  plugin-rexray:
    <<: *default-opts
    image: kaustavb12/rexray-plugin-installer:2021-04-12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - rexray_do_token
    command: sh -c "./install-plugin.sh --driver dobs --version 0.11.4 --do-secret rexray_do_token --do-region nyc3 --do-convert-underscore"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

secrets:
  rexray_do_token:
    external: true
    name: rexray_do_token

